services:
  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    container_name: nginx-rtmp
    privileged: true
    volumes:
      - ./logs:/logs
    ports:
      - "1935:1935"
      - "8080:80"
    cap_add:
      - NET_ADMIN
    # network_mode: "host"
    networks:
      app_net:
        ipv4_address: 192.168.100.2

  publish:
    build:
      context: ./
      dockerfile: ./publish/Dockerfile
    container_name: rtmp-publish
    privileged: true
    depends_on:
      - server
    volumes:
      - ./publish/video_samples:/video_samples
      - ./logs:/logs
    cap_add:
      - NET_ADMIN
    networks:
      app_net:
        ipv4_address: 192.168.100.3

  admin:
    build:
      context: ./
      dockerfile: ./admin/Dockerfile
    container_name: admin
    cap_add:
      - NET_ADMIN
    privileged: true
    network_mode: "host"
    pid: "host"
    volumes:
      - /:/host


# networks:
#   app_net:
#     driver: macvlan
#     driver_opts:
#       parent: eth0
#     ipam:
#       config:
#         - subnet: 192.168.100.0/24
#           gateway: 192.168.100.1
networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24